### PR TITLE
Gunicorn setup

### PR DESCRIPTION
**Pull request by bhgrant8**
This branch is meant to address #24 Create a Deploy Ready version of Crash API 
Specifically:

 * WSGI HTTP Server - Gunicorn
 * Serves staticfiles in prod mode - implements whitenoise correctly, collects static @ runtime, and has staticfiles in .gitignore (http://whitenoise.evans.io/en/stable/django.html)
 * config/secrets handled through an env file
*  use a gunicorn.config.py file for configuring gunicorn
*  using gevent/async workers correctly including any monkey-patching as needed?
*  if monkeypatching, way to override to allow dev. server to work in local development
*  Create a staging docker-compose to test the deploy version locally

### CODE REVIEW

**Comment by znmeb** [comment]
I have zero expertise in Gunicorn - there must be someone else who can review this ;-)

**Comment by kiniadit** [comment]
Not the most familiar with this either. Will we be using Nginx as the web server with Gunicorn as the gateway?

https://codingstartups.com/deploy-django-nginx-gunicorn-postgresql-supervisor/

**Comment by bhgrant8** [comment]
By using WhiteNoise (http://whitenoise.evans.io/en/stable/), combined with the load balancing we are using through AWS, we are actually able to cut out the need for nginx, and simplify the stack. Gunicorn then functions as the http server directly and can host static files in production mode through this plugin.

Ignoring the exact implementation steps in favor of the ones in official docs linked above, this blog post is a good overview of the benefits/costs of this approach:
http://andrealmar.com/2016/03/django-whitenoise/

I'll note here that we are not using a CDN at this time, and would rather not worry about this unless we find a need to scale in this way.

**Comment by kiniadit** [comment]
Ok, thanks for sharing. I tested this earlier today and runs fine. I'm ok with merging this.

**Review by kiniadit — APPROVED** [review]
No breaking issues. Ok to merge.

**Pull request merged**
